export const SERVICE_FEE = 100;

export const SELLING_AGENCY_COMMISSION_PERCENTAGE = 25;
export const LISTING_AGENCY_COMMISSION_PERCENTAGE = 25;

export const SELLING_AGENT_COMMISSION_PERCENTAGE = 25;
export const LISTING_AGENT_COMMISSION_PERCENTAGE = 25;
